pipeline {
    //agent {
    //    docker { image 'node:14-alpine' }
    //}
    agent {
        //dockerfile {
            //filename 'Dockerfile.build'
            //dir 'rsc'
            //label 'master'
            //additionalBuildArgs  '--build-arg version=1.0.2'
            //args '-v /tmp:/tmp'
        //}
        dockerfile true
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
